# Generated by Django 3.0.4 on 2020-04-04 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patrol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Troop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('district', models.CharField(max_length=128)),
                ('council', models.CharField(max_length=128)),
                ('scoutmaster', models.CharField(max_length=128)),
                ('emergency_contact_num', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Scout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('patrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Troop')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('submit_date', models.DateTimeField(auto_now_add=True)),
                ('submit_user', models.CharField(max_length=128)),
                ('comment', models.CharField(max_length=256)),
                ('patrol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Patrol')),
                ('scout', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Scout')),
            ],
        ),
        migrations.AddField(
            model_name='patrol',
            name='troop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Troop'),
        ),
    ]
