# Generated by Django 3.0.4 on 2020-04-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scout',
            name='patrol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Patrol'),
        ),
    ]
